version: "1.0"
info:
  model: int-scaffold
packages:
- name: Git_projectProject
  gitServerName: moaa
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: moaaSoftwareAG
  gitBranch: main
services:
- serviceName: project.git_project.integrations:flow_service
  packages:
  - name: Git_projectProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1962
